// import '../imports/startup/client/serviceWorker'
import '../imports/startup/client/i18n'
import '../imports/startup/client/routes'
import '../imports/startup/client/minimalui'
import '../imports/startup/client/styles'
import '../imports/startup/client/templates'
import './main.scss'
import './main.html'
