import '../imports/startup/client/i18n'
import '../imports/startup/client/routes'
import '../imports/startup/client/bootstrap'
import '../imports/startup/client/fontawesome'
import '../imports/startup/client/minimalui'
import '../imports/startup/both/collections'
import './main.scss'
import './main.html'
