import '../imports/startup/server/validateSettings'
import '../imports/startup/server/environment'
import '../imports/startup/both/schema'
import '../imports/startup/server/content'
import '../imports/startup/server/admin'
import '../imports/startup/server/accounts'
import '../imports/startup/server/users'
import '../imports/startup/server/teacherContexts'
