name: Stylelint
on: [push,pull_request]

jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          stylelint_input: '**/*.scss'
          stylelint_config: '.stylelintrc.json'
          level: 'error'
